name: Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    env:
      NAME: WatchAlong
      RELEASE_ZIP_FILENAME: ${{ github.event.repository.name }}-${{ github.ref_name }}-win-x64.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
      - name: Build
        run: make build
      - name: Create release ZIP file
        run: |
          Rename-Item out ${{ env.NAME }}
          Compress-Archive ${{ env.NAME }} ${{ env.RELEASE_ZIP_FILENAME }}
      - name: Release on GitHub
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          files: ${{ env.RELEASE_ZIP_FILENAME }}
      - name: Generate signed build provenance attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ env.RELEASE_ZIP_FILENAME }}
